# Generated by Django 4.1.7 on 2023-03-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("author", models.CharField(max_length=60)),
                ("publisher", models.CharField(max_length=60)),
                ("datePublished", models.DateField()),
            ],
        ),
    ]
