# Generated by Django 4.1.7 on 2023-03-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_uploadfile_upload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="uuid",
            field=models.CharField(default="1", max_length=36),
            preserve_default=False,
        ),
    ]
