# Generated by Django 4.1.7 on 2023-03-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_book_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=160)),
                ("original_filename", models.CharField(max_length=120)),
                ("owner", models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name="UploadFile",
        ),
    ]
