# Generated by Django 4.1.7 on 2023-03-07 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_filelink_delete_uploadfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="id",
        ),
        migrations.AddField(
            model_name="book",
            name="csv_file",
            field=models.CharField(default="bookcsv.csv", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
