# Generated by Django 4.1.7 on 2023-03-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_book_id_book_csv_file_alter_book_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="owner",
            field=models.CharField(default="chris", max_length=120),
            preserve_default=False,
        ),
    ]
