# Generated by Django 4.1.7 on 2023-03-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_book_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default="1",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="uuid",
            field=models.UUIDField(editable=False),
        ),
    ]
